//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIFTAN.DAL.DB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FREELANCER_DOC_INFO
    {
        public string Freelancer_Id { get; set; }
        public string NID_Path { get; set; }
        public string Picture_Path { get; set; }
        public string PVC_Path { get; set; }
    }
}
