//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIFTAN.DAL.DB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FREELANCER_EXPERIENCE_INFO
    {
        public int Id { get; set; }
        public string Freelancer_Id { get; set; }
        public string Organization { get; set; }
        public string Designation { get; set; }
        public string Responsibilities { get; set; }
        public string AreaofExperiences { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
    }
}
