//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIFTAN.DAL.DB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FREELANCER_EDUCATION_INFO
    {
        public int Id { get; set; }
        public string Freelancer_Id { get; set; }
        public string Degree { get; set; }
        public string Institute { get; set; }
        public Nullable<int> Year { get; set; }
        public string Result { get; set; }
        public string Subject { get; set; }
    }
}
