//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIFTAN.DAL.DB.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SciftanDbContext : DbContext
    {
        public SciftanDbContext()
            : base("name=SciftanDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FREELANCER_PERSONAL_INFO> FREELANCER_PERSONAL_INFO { get; set; }
        public virtual DbSet<FREELANCER_EDUCATION_INFO> FREELANCER_EDUCATION_INFO { get; set; }
        public virtual DbSet<FREELANCER_CAREER_OBJECTIVE> FREELANCER_CAREER_OBJECTIVE { get; set; }
        public virtual DbSet<FREELANCER_DOC_INFO> FREELANCER_DOC_INFO { get; set; }
        public virtual DbSet<FREELANCER_EXPERIENCE_INFO> FREELANCER_EXPERIENCE_INFO { get; set; }
        public virtual DbSet<SKILL> SKILLs { get; set; }
        public virtual DbSet<FREELANCER_SKILL_INFO> FREELANCER_SKILL_INFO { get; set; }

    }
}
